---
- name: Template Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify: Reload caddy

- name: Enable and start caddy
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: started
