---
caddy_http_port: 80
caddy_https_port: 443

ufw_rules:
  - rule: allow
    port: "{{ caddy_http_port }}"
    proto: tcp
    src: "{{ ufw_lan_subnet }}"
  - rule: allow
    port: "{{ caddy_https_port }}"
    proto: tcp
    src: "{{ ufw_lan_subnet }}"
