---
opentrashmail_data_dir: /opt/opentrashmail
opentrashmail_domain: exilemail.xyz
opentrashmail_http_port: 8080
opentrashmail_smtp_port: 25

ufw_rules:
  - rule: allow
    port: "{{ opentrashmail_smtp_port }}"
    proto: tcp
  - rule: allow
    port: "{{ opentrashmail_http_port }}"
    proto: tcp
    src: "{{ ufw_lan_subnet }}"
